### ISSUE TITLE
Missing depenceny

### ISSUE THREAD

**Issue by Dungeonseeker** [pufferpanel/documentation#12]
So I believe this is probably a steamcmd issue rather than a PP one however on a clean install running on Ubuntu server I was getting errors when trying to run steamcmd.

After some digging I found out that steamcmd REQUIRES lib32gcc1to be installed otherwise it throws up "file doesn't exist" errors.

Any chance you can add it as a dependency in future builds? Would really help out people who are new to Linux and might think that PP is broken on a clean install.

**Comment by Dreamedc2015** [comment]
i dont think the panel should be bloated by extra dependencies
but maybe it should be documented idk

**Comment by nepcore** [comment]
#15 adds information about that dependency to the documentation

If we were to add lib32gcc1 as a dependency to the PufferPanel package we'd by the same logic need to also add java (as well as others probably) to the dependencies as that's being used by some templates that are on the template repository as well  
That would bring about a lot of bloat for every user who doesn't need all these dependencies, so I'd say documenting that, sure (happened already), but depending on it is probably not going to happen
